language: generic

env:
  - PPA=yes

install:
  - if [ x"$PPA" == "xyes" ] ; then sudo add-apt-repository ppa:pi-rho/dev -y; fi
  - sudo apt-get update -q
  - sudo apt-get install vim-nox

before_script:
  - vim --version
  - chmod +x ./test/test-highlightedyank.sh

script:
  - ./test/test-highlightedyank.sh
